### ISSUE TITLE
What is your name? - Photo selection + Lesson completion

### ISSUE THREAD

**Issue by awolowiecki720** [eklavyamirani/DTML.EduBot#36]
When identifying a photo, the user must select the correct answer. While in this state, the user is still allowed to type into the text box. When done, this throws a null reference exception and resets the bot.

**Comment by awolowiecki720** [comment]
Also, along the same line, it looks like when a lesson finishes the bot resets back to asking what your name is...that should not be the default starting point for the bot, since it only needs to ask your name once.

**Comment by dalin7** [comment]
Fixed the null reference exception. Created a separate issue for lesson completion problem: #39
