### ISSUE TITLE
UserData leak between mutliple sessions when Anonymous users are using the bot simultaneously.

### ISSUE THREAD

**Issue by eklavyamirani** [eklavyamirani/DTML.EduBot#37]
All Anonymous users have an id: Guest, so when we store user data, multiple guest users will end up sharing common User Data, and it will cause the data in one session to move into another session.

**Comment by sinyaa** [comment]
Resolved by PR into DTML:
user: { name: '@userName', id: '@id' }

Before id was set to "Guest" and the name was not set. MBF uses "User" is From.Name is empty.
https://kabroo.visualstudio.com/DTML.org/_git/DTML/pullrequest/253
